export const constantes = () => {
    return {
        url_principal: [
            {url: 'https://manejo.tvi-shop.com/api'}
        ],
        lista_tipo_documento: [
            {documento: 'D.N.I'},
            {documento: 'Pasaporte'},
            {documento: 'C.E'},
            {documento: 'Otro'}
        ],
        lista_respuestas: [
            'respuesta_uno',
            'respuesta_dos',
            'respuesta_tres',
            'respuesta_cuatro',
            'respuesta_cinco',
            'respuesta_seis',
            'respuesta_siete',
            'respuesta_ocho',
            'respuesta_nueve',
            'respuesta_diez',
            'respuesta_once',
            'respuesta_doce',
            'respuesta_trece',
            'respuesta_catorce',
            'respuesta_quince',
            'respuesta_diezyseis',
            'respuesta_diezysiete',
            'respuesta_diezyocho',
            'respuesta_diezynueve',
            'respuesta_veinte',
            'respuesta_veinteyuno',
            'respuesta_veinteydos',
            'respuesta_veinteytres',
            'respuesta_veinteycuatro',
            'respuesta_veinteycinco',
            'respuesta_veinteyseis',
            'respuesta_veinteysiete',
            'respuesta_veinteyocho',
            'respuesta_veinteynueve',
            'respuesta_treinta',
            'respuesta_treintayuno',
            'respuesta_treintaydos',
            'respuesta_treintaytres',
            'respuesta_treintaycuatro',
            'respuesta_treintaycinco',
            'respuesta_treintayseis',
            'respuesta_treintaysiete',
            'respuesta_treintayocho',
            'respuesta_treintaynueve',
            'respuesta_cuarenta'
        ],
        lista_correctas: [
            'correcta_uno',
            'correcta_dos',
            'correcta_tres',
            'correcta_cuatro',
            'correcta_cinco',
            'correcta_seis',
            'correcta_siete',
            'correcta_ocho',
            'correcta_nueve',
            'correcta_diez',
            'correcta_once',
            'correcta_doce',
            'correcta_trece',
            'correcta_catorce',
            'correcta_quince',
            'correcta_diezyseis',
            'correcta_diezysiete',
            'correcta_diezyocho',
            'correcta_diezynueve',
            'correcta_veinte',
            'correcta_veinteyuno',
            'correcta_veinteydos',
            'correcta_veinteytres',
            'correcta_veinteycuatro',
            'correcta_veinteycinco',
            'correcta_veinteyseis',
            'correcta_veinteysiete',
            'correcta_veinteyocho',
            'correcta_veinteynueve',
            'correcta_treinta',
            'correcta_treintayuno',
            'correcta_treintaydos',
            'correcta_treintaytres',
            'correcta_treintaycuatro',
            'correcta_treintaycinco',
            'correcta_treintayseis',
            'correcta_treintaysiete',
            'correcta_treintayocho',
            'correcta_treintaynueve',
            'correcta_cuarenta'
        ]
    }
}